name = "ariady-putra/time_util"
version = "0.0.0"
license = "Apache-2.0"
description = "An Aiken utility library to help comparing time intervals"

[repository]
user = "ariady-putra"
project = "time_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
