name = "aiken-extra/time_util"
version = "5.170.202312"
license = "Apache-2.0"
description = "An Aiken utility library to help comparing time intervals"

[repository]
user = "aiken-extra"
project = "time_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
